name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Ou a branch principal do seu repositório
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
